# Generated by Django 4.1.5 on 2023-01-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserBot',
        ),
    ]
