# Generated by Django 4.1.5 on 2023-02-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dnevnik_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_training', models.DateTimeField(auto_now_add=True)),
                ('end_training', models.DateTimeField()),
                ('dnevnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.dnevnik')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.training')),
            ],
        ),
    ]
