# Generated by Django 4.1.5 on 2023-02-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_dnevnik_training'),
    ]

    operations = [
    ]
