# Generated by Django 4.1.5 on 2023-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_user_age_alter_user_gender_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('M/F', 'Male/Female')], max_length=3),
        ),
    ]
