# Generated by Django 4.1.5 on 2023-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_dnevnik_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevnik',
            name='trainings',
            field=models.ManyToManyField(through='tgbot.Dnevnik_training', to='tgbot.training'),
        ),
    ]
