# Generated by Django 4.1.5 on 2023-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_training_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='muscle_group',
            field=models.CharField(choices=[('Спина', 'Спина'), ('Грудь', 'Грудь'), ('Ноги', 'Ноги'), ('Руки', 'Руки')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('M/F', 'Male/Female')], default=None, max_length=3, null=True),
        ),
    ]
