# Generated by Django 4.1.5 on 2023-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_training_muscle_group_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('Fast', 'Быстрая'), ('Pers', 'Персональная')], default=None, max_length=255),
        ),
    ]
