# Generated by Django 4.1.5 on 2023-01-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='muscle_group',
            field=models.CharField(choices=[('Спина', 'Спина'), ('Грудь', 'Грудь'), ('Ноги', 'Ноги'), ('Руки', 'Руки'), ('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Трапеции', 'Трапеции'), ('Плечи', 'Плечи'), ('Пресс', 'Пресс'), ('Разминка', 'Разминка'), ('Функциональная', 'Функциональная'), ('Кардио', 'Кардио')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('M/F', 'М/Ж')], default=None, max_length=3, null=True),
        ),
    ]
