# Generated by Django 4.1.5 on 2023-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_dnevnik_trainings_end_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevnik_trainings',
            name='end_training',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
